#!/usr/bin/env bash
# This is a simple bash scripts runs python unittesting
# module from the current working directory.
#
# A simple call on the file will do: $ ./unittest

python3 -m unittest discover tests
